# Generated by Django 2.1.5 on 2019-02-10 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_auto_20190208_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selections',
            name='picks',
        ),
        migrations.AddField(
            model_name='selection',
            name='selections',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pool.Selections'),
            preserve_default=False,
        ),
    ]
