# Generated by Django 2.1.5 on 2019-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20190210_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('L', 'Lives'), ('D', 'Dies')], default='L', max_length=1),
            preserve_default=False,
        ),
    ]
