# Generated by Django 2.1.5 on 2019-02-13 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_character_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_character', to='pool.Character')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_character', to='pool.Character')),
                ('selections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.Selections')),
            ],
        ),
    ]
